sudo: required
language: go
go:
  - "1.12beta2"
go_import_path: github.com/xiaokangwang/AndroidLibV2ray
git:
  depth: 1
addons:
  apt:
    update: true
before_script:
- sudo ntpdate -u time.google.com
- date
- make all
- make downloadGoMobile
- make buildVGO
script:
- go test -p 1 -tags json -v github.com/xiaokangwang/AndroidLibV2ray/...
after_success:
deploy:
  provider: releases
  api_key:
    secure: "ISqQ9Pive2oVhvA8/J8oCvAEG+33pzuCblXaHdO8SrgiWYNlNsP+5NHdHNMKepzpWIdYZqO7MGfAhG+z+Z+X4hlYWsTnji6U2ibpfSRzZ2c8XNAzn+7sLwK8HmUQ0h4I0DmJh18D7uIOyQHEmzIe95T6FNfqiuqCtnZ+X52X/LpMCnh9DOjv8VS5TB0x62Z4U0UjJJofCIRTK1iKM5UBmFF1mZ8Gd5sWp3X07PNOBZbt01qy7qPRT/YLFhNLBBtElk6ax3AkNb8A2xvlsrczbgEaYUHiZFVIPDJpsAYIzJC21t1gznuYThLrHlZ+iz7JVqfjjNl3hwLeqWJ+WzNYK9B4hsV/Gn9+2Owa5LOgo3Y1nOCitzRH5Ygc3U8WSUb53Pgji23qhHIJ4pIKhUgi8bA6r3K1vE0E10CGpZCeKkqtUqXzz0AXWqMGq6abM2/uag6j+CKWIRtBGI/TliPqllaK++ba3iz5iVMl7IPE4ab4vhBUNqYmjcK1z1xL2yNH6FwSfSkiCMllgH0kLP3BK1T1RSCbPMiiHk63Y91WQ0OEdcDx15+875yct3Q2MrgMDYzqc53znjANWrHLgunfpvEyeslGHVpjqCsFDh9BO9RV+tvOaiEIH5crcnMxIkDkFCPWGwuCKmvcLKQ9FjpnC8wr/hLS/Um7CB9pkj4HO68="
  file:
    - libv2ray.aar
  skip_cleanup: true
  on:
    tags: true
